// === ДАННЫЕ — СЛОВА ===
window.WORDS_DATA = {
  "meta": {
    "title": "Вокабуляр",
    "description": "Слова из лекций"
  },
  "topics": [
    {
      "id": "lektion13",
      "title": "Лекция 13 — Orientierung in der Stadt",
      "words": [
        { "id": "w001", "de": "der Bezirk", "ru": "район", "example": "", "level": "A1" },
        { "id": "w002", "de": "der Fahrradweg", "ru": "велосипедная дорожка", "example": "", "level": "A1" },
        { "id": "w003", "de": "der Fußweg", "ru": "тротуар", "example": "", "level": "A1" },
        { "id": "w004", "de": "der Stadtplan", "ru": "план, карта города", "example": "", "level": "A1" },
        { "id": "w005", "de": "der Stadtrand", "ru": "окраина города", "example": "", "level": "A1" },
        { "id": "w006", "de": "die Ampel", "ru": "светофор", "example": "", "level": "A1" },
        { "id": "w007", "de": "die Brücke", "ru": "мост", "example": "", "level": "A1" },
        { "id": "w008", "de": "die Ecke", "ru": "угол", "example": "", "level": "A1" },
        { "id": "w009", "de": "die Kreuzung", "ru": "перекресток", "example": "", "level": "A1" },
        { "id": "w010", "de": "die Linie", "ru": "линия, маршрут (транспорта)", "example": "", "level": "A1" },
        { "id": "w011", "de": "die Richtung", "ru": "направление", "example": "", "level": "A1" },
        { "id": "w012", "de": "die Seite", "ru": "сторона", "example": "", "level": "A1" },
        { "id": "w013", "de": "das Rathaus", "ru": "ратуша", "example": "", "level": "A1" },
        { "id": "w014", "de": "das Schloss", "ru": "замок", "example": "", "level": "A1" },
        { "id": "w015", "de": "das Ticket", "ru": "билет", "example": "", "level": "A1" },
        { "id": "w016", "de": "das Tor", "ru": "ворота", "example": "", "level": "A1" },
        { "id": "w017", "de": "Wie komme ich zu ...?", "ru": "Как (мне) пройти к...", "example": "", "level": "A1" },
        { "id": "w018", "de": "Gehen Sie ...", "ru": "Идите...", "example": "", "level": "A1" },
        { "id": "w019", "de": "geradeaus", "ru": "прямо", "example": "", "level": "A1" },
        { "id": "w020", "de": "(nach) links", "ru": "(на)лево", "example": "", "level": "A1" },
        { "id": "w021", "de": "(nach) rechts", "ru": "(на)право", "example": "", "level": "A1" },
        { "id": "w022", "de": "um die Ecke", "ru": "за угол", "example": "", "level": "A1" },
        { "id": "w023", "de": "Es ist ...", "ru": "Это находится...", "example": "", "level": "A1" },
        { "id": "w024", "de": "auf der linken Seite", "ru": "на левой стороне", "example": "", "level": "A1" },
        { "id": "w025", "de": "auf der rechten Seite", "ru": "на правой стороне", "example": "", "level": "A1" },
        { "id": "w026", "de": "an der Ecke", "ru": "на углу", "example": "", "level": "A1" },
        { "id": "w027", "de": "am Ende", "ru": "в конце", "example": "", "level": "A1" },
        { "id": "w028", "de": "(nicht) weit", "ru": "(не) далеко", "example": "", "level": "A1" },
        { "id": "w029", "de": "Nehmen Sie ...", "ru": "Вам нужен... (транспорт, улица)", "example": "", "level": "A1" },
        { "id": "w030", "de": "den Bus, die U-Bahn Linie 3", "ru": "автобус, метро третьего маршрута", "example": "", "level": "A1" },
        { "id": "w031", "de": "die erste Straße links", "ru": "первая улица налево", "example": "", "level": "A1" },
        { "id": "w032", "de": "die zweite Straße rechts", "ru": "вторая улица направо", "example": "", "level": "A1" }
      ]
    },
    {
      "id": "lektion14",
      "title": "Лекция 14 — Mein Tag",
      "words": [
        { "id": "w033", "de": "der Morgen", "ru": "утро (04-10 Uhr)", "example": "", "level": "A1" },
        { "id": "w034", "de": "der Vormittag", "ru": "первая пол. дня (10-12 Uhr)", "example": "", "level": "A1" },
        { "id": "w035", "de": "der Mittag", "ru": "полдень/обед (12-14 Uhr)", "example": "", "level": "A1" },
        { "id": "w036", "de": "der Nachmittag", "ru": "вторая пол. дня (14-18 Uhr)", "example": "", "level": "A1" },
        { "id": "w037", "de": "der Abend", "ru": "вечер (18-23 Uhr)", "example": "", "level": "A1" },
        { "id": "w038", "de": "die Nacht", "ru": "ночь (23-04 Uhr)", "example": "", "level": "A1" },
        { "id": "w039", "de": "der Montag", "ru": "понедельник", "example": "", "level": "A1" },
        { "id": "w040", "de": "der Dienstag", "ru": "вторник", "example": "", "level": "A1" },
        { "id": "w041", "de": "der Mittwoch", "ru": "среда", "example": "", "level": "A1" },
        { "id": "w042", "de": "der Donnerstag", "ru": "четверг", "example": "", "level": "A1" },
        { "id": "w043", "de": "der Freitag", "ru": "пятница", "example": "", "level": "A1" },
        { "id": "w044", "de": "der Samstag", "ru": "суббота", "example": "", "level": "A1" },
        { "id": "w045", "de": "der Sonntag", "ru": "воскресенье", "example": "", "level": "A1" },
        { "id": "w046", "de": "anmachen", "ru": "включать", "example": "", "level": "A1" },
        { "id": "w047", "de": "anrufen", "ru": "звонить (по телефону)", "example": "", "level": "A1" },
        { "id": "w048", "de": "anziehen", "ru": "надевать", "example": "", "level": "A1" },
        { "id": "w049", "de": "aufstehen", "ru": "вставать", "example": "", "level": "A1" },
        { "id": "w050", "de": "ausgehen", "ru": "выходить; пойти куда-нибудь (в кино, театр и т.п.)", "example": "", "level": "A1" },
        { "id": "w051", "de": "ausmachen", "ru": "выключать", "example": "", "level": "A1" },
        { "id": "w052", "de": "aussteigen", "ru": "выходить (из транспорта)", "example": "", "level": "A1" },
        { "id": "w053", "de": "ausziehen", "ru": "снимать (одежду)", "example": "", "level": "A1" },
        { "id": "w054", "de": "einkaufen", "ru": "делать покупки", "example": "", "level": "A1" },
        { "id": "w055", "de": "einsteigen", "ru": "садиться (в транспорт)", "example": "", "level": "A1" },
        { "id": "w056", "de": "fernsehen", "ru": "смотреть ТВ", "example": "", "level": "A1" },
        { "id": "w057", "de": "mitnehmen", "ru": "брать с собой", "example": "", "level": "A1" },
        { "id": "w058", "de": "zurückgeben", "ru": "возвращать", "example": "", "level": "A1" },
        { "id": "w059", "de": "zurückkommen", "ru": "возвращаться", "example": "", "level": "A1" },
        { "id": "w060", "de": "das Bett machen", "ru": "убирать постель", "example": "", "level": "A1" },
        { "id": "w061", "de": "die Zähne putzen", "ru": "чистить зубы", "example": "", "level": "A1" },
        { "id": "w062", "de": "das Geschirr spülen", "ru": "мыть посуду", "example": "", "level": "A1" },
        { "id": "w063", "de": "packen", "ru": "паковать, собирать вещь", "example": "", "level": "A1" },
        { "id": "w064", "de": "die Sache", "ru": "вещь", "example": "", "level": "A1" },
        { "id": "w065", "de": "zu Fuß gehen", "ru": "идти пешком", "example": "", "level": "A1" },
        { "id": "w066", "de": "die Haltestelle", "ru": "остановка (место остановки)", "example": "", "level": "A1" },
        { "id": "w067", "de": "müde", "ru": "усталый", "example": "", "level": "A1" },
        { "id": "w068", "de": "einschlafen", "ru": "засыпать", "example": "", "level": "A1" }
      ]
    },
    {
      "id": "lektion15",
      "title": "Лекция 15 — Am Bahnhof",
      "words": [
        { "id": "w069", "de": "der Bahnsteig", "ru": "платформа", "example": "", "level": "A1" },
        { "id": "w070", "de": "der Bahnhof", "ru": "вокзал", "example": "", "level": "A1" },
        { "id": "w071", "de": "der Fahrgast", "ru": "пассажир", "example": "", "level": "A1" },
        { "id": "w072", "de": "der Fahrplan", "ru": "расписание", "example": "", "level": "A1" },
        { "id": "w073", "de": "der Platz", "ru": "место (сиденье)", "example": "", "level": "A1" },
        { "id": "w074", "de": "der Schaffner", "ru": "проводник", "example": "", "level": "A1" },
        { "id": "w075", "de": "der Schalter", "ru": "окошко (кассы)", "example": "", "level": "A1" },
        { "id": "w076", "de": "der Schlafwagen", "ru": "спальный вагон", "example": "", "level": "A1" },
        { "id": "w077", "de": "der Wagen", "ru": "вагон", "example": "", "level": "A1" },
        { "id": "w078", "de": "die Abfahrt", "ru": "отъезд, отправление", "example": "", "level": "A1" },
        { "id": "w079", "de": "die Ankunft", "ru": "прибытие", "example": "", "level": "A1" },
        { "id": "w080", "de": "die Fahrkarte", "ru": "билет", "example": "", "level": "A1" },
        { "id": "w081", "de": "die Fahrt", "ru": "поездка, езда", "example": "", "level": "A1" },
        { "id": "w082", "de": "die Station", "ru": "станция", "example": "", "level": "A1" },
        { "id": "w083", "de": "die Verspätung", "ru": "опоздание", "example": "", "level": "A1" },
        { "id": "w084", "de": "das Abteil", "ru": "купе", "example": "", "level": "A1" },
        { "id": "w085", "de": "das Gleis", "ru": "путь (железнодорожный)", "example": "", "level": "A1" }
      ]
    },
    {
      "id": "lektion16",
      "title": "Лекция 16 — Freizeit",
      "words": [
        { "id": "w086", "de": "der Aquapark", "ru": "аквапарк", "example": "", "level": "A1" },
        { "id": "w087", "de": "der Ausflug", "ru": "поездка, экскурсия", "example": "", "level": "A1" },
        { "id": "w088", "de": "der Film", "ru": "фильм", "example": "", "level": "A1" },
        { "id": "w089", "de": "der Freizeitpark", "ru": "парк развлечений", "example": "", "level": "A1" },
        { "id": "w090", "de": "der Krimi", "ru": "детектив", "example": "", "level": "A1" },
        { "id": "w091", "de": "der Strand", "ru": "пляж", "example": "", "level": "A1" },
        { "id": "w092", "de": "der Urlaub", "ru": "отпуск", "example": "", "level": "A1" },
        { "id": "w093", "de": "die Ausstellung", "ru": "выставка", "example": "", "level": "A1" },
        { "id": "w094", "de": "die Diskothek", "ru": "дискотека", "example": "", "level": "A1" },
        { "id": "w095", "de": "die Einladung", "ru": "приглашение", "example": "", "level": "A1" },
        { "id": "w096", "de": "die Freizeit", "ru": "свободное время, досуг", "example": "", "level": "A1" },
        { "id": "w097", "de": "die Kneipe", "ru": "пивная", "example": "", "level": "A1" },
        { "id": "w098", "de": "die Unterhaltung", "ru": "развлечение", "example": "", "level": "A1" },
        { "id": "w099", "de": "die Vorstellung", "ru": "представление", "example": "", "level": "A1" },
        { "id": "w100", "de": "das Fest", "ru": "праздник", "example": "", "level": "A1" },
        { "id": "w101", "de": "das Ticket", "ru": "билет", "example": "", "level": "A1" },
        { "id": "w102", "de": "das Treffen", "ru": "встреча", "example": "", "level": "A1" },
        { "id": "w103", "de": "die Ferien (pl.)", "ru": "каникулы", "example": "", "level": "A1" },
        { "id": "w104", "de": "spazieren gehen", "ru": "ходить гулять", "example": "", "level": "A1" },
        { "id": "w105", "de": "verbringen", "ru": "проводить (время и т.п.)", "example": "", "level": "A1" },
        { "id": "w106", "de": "ins Grüne fahren", "ru": "ехать на природу", "example": "", "level": "A1" },
        { "id": "w107", "de": "besonders", "ru": "особенно", "example": "", "level": "A1" },
        { "id": "w108", "de": "das Picknick", "ru": "пикник", "example": "", "level": "A1" },
        { "id": "w109", "de": "der Fluss", "ru": "река", "example": "", "level": "A1" },
        { "id": "w110", "de": "in der Sonne liegen", "ru": "загорать", "example": "", "level": "A1" },
        { "id": "w111", "de": "Boot fahren", "ru": "кататься на лодке", "example": "", "level": "A1" },
        { "id": "w112", "de": "Das macht mir Spaß.", "ru": "Это доставляет мне удовольствие.", "example": "", "level": "A1" },
        { "id": "w113", "de": "zu Besuch gehen", "ru": "ходить в гости", "example": "", "level": "A1" },
        { "id": "w114", "de": "einladen", "ru": "приглашать", "example": "", "level": "A1" }
      ]
    },
    {
      "id": "lektion17",
      "title": "Лекция 17 — Wohnung",
      "words": [
        { "id": "w115", "de": "der Balkon", "ru": "балкон", "example": "", "level": "A1" },
        { "id": "w116", "de": "der Esstisch", "ru": "обеденный стол", "example": "", "level": "A1" },
        { "id": "w117", "de": "der Fahrstuhl", "ru": "лифт", "example": "", "level": "A1" },
        { "id": "w118", "de": "der Fernseher", "ru": "телевизор", "example": "", "level": "A1" },
        { "id": "w119", "de": "der Flur", "ru": "прихожая", "example": "", "level": "A1" },
        { "id": "w120", "de": "der Fußboden", "ru": "пол", "example": "", "level": "A1" },
        { "id": "w121", "de": "der Geschirrspüler", "ru": "посудомоечная машина", "example": "", "level": "A1" },
        { "id": "w122", "de": "der Haken", "ru": "крючок, вешалка", "example": "", "level": "A1" },
        { "id": "w123", "de": "der Herd", "ru": "плита (кухонная)", "example": "", "level": "A1" },
        { "id": "w124", "de": "der Hocker", "ru": "табурет", "example": "", "level": "A1" },
        { "id": "w125", "de": "der Hof", "ru": "двор", "example": "", "level": "A1" },
        { "id": "w126", "de": "der Keller", "ru": "погреб, подвал", "example": "", "level": "A1" },
        { "id": "w127", "de": "der Kleiderschrank", "ru": "гардероб, платяной шкаф", "example": "", "level": "A1" },
        { "id": "w128", "de": "der Kühlschrank", "ru": "холодильник", "example": "", "level": "A1" },
        { "id": "w129", "de": "der Nachttisch", "ru": "тумбочка, ночной столик", "example": "", "level": "A1" },
        { "id": "w130", "de": "der Spiegel", "ru": "зеркало", "example": "", "level": "A1" },
        { "id": "w131", "de": "der Stock, Stockwerke", "ru": "этаж", "example": "", "level": "A1" },
        { "id": "w132", "de": "der Teppich", "ru": "ковер", "example": "", "level": "A1" },
        { "id": "w133", "de": "die Badewanne", "ru": "ванна", "example": "", "level": "A1" },
        { "id": "w134", "de": "die Couch", "ru": "кушетка", "example": "", "level": "A1" },
        { "id": "w135", "de": "die Decke", "ru": "потолок", "example": "", "level": "A1" },
        { "id": "w136", "de": "die Duschkabine", "ru": "душевая кабина", "example": "", "level": "A1" },
        { "id": "w137", "de": "die Ecke", "ru": "угол", "example": "", "level": "A1" },
        { "id": "w138", "de": "die Gardine", "ru": "занавеска", "example": "", "level": "A1" },
        { "id": "w139", "de": "die Kommode", "ru": "комод", "example": "", "level": "A1" },
        { "id": "w140", "de": "die Küche", "ru": "кухня", "example": "", "level": "A1" },
        { "id": "w141", "de": "die Miete", "ru": "арендная плата, квартплата", "example": "", "level": "A1" },
        { "id": "w142", "de": "die Mikrowelle", "ru": "микроволновая печь", "example": "", "level": "A1" },
        { "id": "w143", "de": "die Mitte", "ru": "середина", "example": "", "level": "A1" },
        { "id": "w144", "de": "die Schrankwand", "ru": "стенка (мебельная)", "example": "", "level": "A1" },
        { "id": "w145", "de": "die Spüle", "ru": "мойка", "example": "", "level": "A1" },
        { "id": "w146", "de": "die Stehlampe", "ru": "торшер", "example": "", "level": "A1" },
        { "id": "w147", "de": "die Tapete", "ru": "обои", "example": "", "level": "A1" },
        { "id": "w148", "de": "die Toilette", "ru": "туалет", "example": "", "level": "A1" },
        { "id": "w149", "de": "die Treppe", "ru": "лестница", "example": "", "level": "A1" },
        { "id": "w150", "de": "die Wand", "ru": "стена (внутри дома)", "example": "", "level": "A1" },
        { "id": "w151", "de": "die Waschmaschine", "ru": "стиральная машина", "example": "", "level": "A1" },
        { "id": "w152", "de": "das Bad, Badezimmer", "ru": "ванная комната", "example": "", "level": "A1" },
        { "id": "w153", "de": "das Dach", "ru": "крыша", "example": "", "level": "A1" },
        { "id": "w154", "de": "das Erdgeschoss", "ru": "первый (земляной) этаж", "example": "", "level": "A1" },
        { "id": "w155", "de": "das Esszimmer", "ru": "столовая", "example": "", "level": "A1" },
        { "id": "w156", "de": "das Fensterbrett", "ru": "подоконник", "example": "", "level": "A1" },
        { "id": "w157", "de": "das Licht", "ru": "свет", "example": "", "level": "A1" },
        { "id": "w158", "de": "das Regal", "ru": "этажерка, стеллаж", "example": "", "level": "A1" },
        { "id": "w159", "de": "das Schlafzimmer", "ru": "спальня", "example": "", "level": "A1" },
        { "id": "w160", "de": "das Sofa", "ru": "диван, софа", "example": "", "level": "A1" },
        { "id": "w161", "de": "das Waschbecken", "ru": "умывальник (раковина)", "example": "", "level": "A1" },
        { "id": "w162", "de": "das Wohnzimmer", "ru": "гостиная", "example": "", "level": "A1" },
        { "id": "w163", "de": "umziehen", "ru": "переезжать", "example": "", "level": "A1" },
        { "id": "w164", "de": "gehen auf", "ru": "выходить на что-л. (об окнах)", "example": "", "level": "A1" },
        { "id": "w165", "de": "der Lärm", "ru": "шум", "example": "", "level": "A1" },
        { "id": "w166", "de": "stören", "ru": "беспокоить", "example": "", "level": "A1" },
        { "id": "w167", "de": "die Treppe hochgehen", "ru": "подниматься по лестнице", "example": "", "level": "A1" },
        { "id": "w168", "de": "die Treppe runtergehen", "ru": "спускаться по лестнице", "example": "", "level": "A1" }
      ]
    },
    {
      "id": "lektion18",
      "title": "Лекция 18 — Zu Besuch",
      "words": [
        { "id": "w169", "de": "Herzlich willkommen!", "ru": "Добро пожаловать!", "example": "", "level": "A1" },
        { "id": "w170", "de": "Wir haben uns lange nicht gesehen.", "ru": "Давно не виделись.", "example": "", "level": "A1" },
        { "id": "w171", "de": "Bis morgen!", "ru": "До завтра!", "example": "", "level": "A1" },
        { "id": "w172", "de": "Bis heute Abend!", "ru": "До вечера!", "example": "", "level": "A1" },
        { "id": "w173", "de": "Mach's gut!", "ru": "Счастливо! Удачи!", "example": "", "level": "A1" },
        { "id": "w174", "de": "Viel Erfolg!", "ru": "Успехов!", "example": "", "level": "A1" },
        { "id": "w175", "de": "Viel Spaß!", "ru": "Желаю хорошо провести время!", "example": "", "level": "A1" },
        { "id": "w176", "de": "Alles Gute!", "ru": "Всего хорошего!", "example": "", "level": "A1" },
        { "id": "w177", "de": "Einverstanden!", "ru": "Согласен! Ладно!", "example": "", "level": "A1" },
        { "id": "w178", "de": "Eine gute Idee!", "ru": "Хорошая мысль!", "example": "", "level": "A1" },
        { "id": "w179", "de": "unbedingt", "ru": "обязательно, непременно", "example": "", "level": "A1" },
        { "id": "w180", "de": "Ich habe nichts dagegen.", "ru": "Я не против.", "example": "", "level": "A1" },
        { "id": "w181", "de": "sehr gern", "ru": "с удовольствием", "example": "", "level": "A1" },
        { "id": "w182", "de": "Ich bin dagegen.", "ru": "Я против.", "example": "", "level": "A1" },
        { "id": "w183", "de": "Das ist unmöglich.", "ru": "Это невозможно.", "example": "", "level": "A1" },
        { "id": "w184", "de": "auf keinen Fall", "ru": "ни в коем случае", "example": "", "level": "A1" },
        { "id": "w185", "de": "Ich kann leider nicht.", "ru": "К сожалению, я не могу.", "example": "", "level": "A1" },
        { "id": "w186", "de": "Das geht leider nicht.", "ru": "К сожалению, это не получится.", "example": "", "level": "A1" },
        { "id": "w187", "de": "Wie geht's?", "ru": "Как дела?", "example": "", "level": "A1" },
        { "id": "w188", "de": "grüßen", "ru": "приветствовать, здороваться", "example": "", "level": "A1" },
        { "id": "w189", "de": "reinkommen", "ru": "входить", "example": "", "level": "A1" },
        { "id": "w190", "de": "Platz nehmen", "ru": "садиться, занимать место", "example": "", "level": "A1" },
        { "id": "w191", "de": "einschenken", "ru": "наливать", "example": "", "level": "A1" },
        { "id": "w192", "de": "war", "ru": "был, была", "example": "", "level": "A1" },
        { "id": "w193", "de": "besonders", "ru": "особенно", "example": "", "level": "A1" },
        { "id": "w194", "de": "etwa", "ru": "примерно, около (о времени)", "example": "", "level": "A1" },
        { "id": "w195", "de": "klingen", "ru": "звучать", "example": "", "level": "A1" },
        { "id": "w196", "de": "Grüß ... von mir!", "ru": "Передай ... привет от меня!", "example": "", "level": "A1" }
      ]
    },
    {
      "id": "lektion19",
      "title": "Лекция 19 — Ein Brief",
      "words": [
        { "id": "w197", "de": "der Absender", "ru": "отправитель", "example": "", "level": "A1" },
        { "id": "w198", "de": "der Empfänger", "ru": "получатель, адресат", "example": "", "level": "A1" },
        { "id": "w199", "de": "der Umschlag", "ru": "конверт", "example": "", "level": "A1" },
        { "id": "w200", "de": "die Adresse / Anschrift", "ru": "адрес", "example": "", "level": "A1" },
        { "id": "w201", "de": "die Briefmarke", "ru": "почтовая марка", "example": "", "level": "A1" },
        { "id": "w202", "de": "die Postkarte", "ru": "открытка", "example": "", "level": "A1" },
        { "id": "w203", "de": "die Postleitzahl", "ru": "индекс", "example": "", "level": "A1" },
        { "id": "w204", "de": "das Datum", "ru": "дата", "example": "", "level": "A1" },
        { "id": "w205", "de": "Lieber Markus / Liebe Stefanie", "ru": "Дорогой... / Дорогая... (неофиц.)", "example": "", "level": "A1" },
        { "id": "w206", "de": "Sehr geehrter Herr / Frau", "ru": "Уважаемый г-н / г-жа! (офиц.)", "example": "", "level": "A1" },
        { "id": "w207", "de": "Sehr geehrte Damen und Herren", "ru": "Уважаемые дамы и господа!", "example": "", "level": "A1" },
        { "id": "w208", "de": "Liebe Grüße / Viele Grüße", "ru": "С наилучшими пожеланиями (неофиц.)", "example": "", "level": "A1" },
        { "id": "w209", "de": "Mit freundlichen Grüßen", "ru": "С дружеским приветом (офиц.)", "example": "", "level": "A1" },
        { "id": "w210", "de": "endlich", "ru": "наконец (-то)", "example": "", "level": "A1" },
        { "id": "w211", "de": "genug", "ru": "довольно, достаточно", "example": "", "level": "A1" },
        { "id": "w212", "de": "das Fach", "ru": "предмет (учебный)", "example": "", "level": "A1" },
        { "id": "w213", "de": "der Strand", "ru": "пляж", "example": "", "level": "A1" },
        { "id": "w214", "de": "heiß", "ru": "жарко", "example": "", "level": "A1" },
        { "id": "w215", "de": "die Kirche", "ru": "церковь", "example": "", "level": "A1" },
        { "id": "w216", "de": "das Schloss", "ru": "дворец", "example": "", "level": "A1" },
        { "id": "w217", "de": "ich habe Glück", "ru": "мне везет", "example": "", "level": "A1" },
        { "id": "w218", "de": "unterwegs", "ru": "по дороге, в пути", "example": "", "level": "A1" },
        { "id": "w219", "de": "üben", "ru": "упражняться, тренироваться", "example": "", "level": "A1" },
        { "id": "w220", "de": "die Geduld", "ru": "терпение", "example": "", "level": "A1" },
        { "id": "w221", "de": "Das ist sehr nett von ...", "ru": "Это очень мило со стороны ...", "example": "", "level": "A1" },
        { "id": "w222", "de": "Das war's.", "ru": "Вот и все.", "example": "", "level": "A1" },
        { "id": "w223", "de": "entschuldigen", "ru": "прощать, извинять", "example": "", "level": "A1" },
        { "id": "w224", "de": "hoffen", "ru": "надеяться", "example": "", "level": "A1" },
        { "id": "w225", "de": "schicken", "ru": "посылать", "example": "", "level": "A1" },
        { "id": "w226", "de": "wünschen", "ru": "желать", "example": "", "level": "A1" }
      ]
    },
    {
      "id": "lektion20",
      "title": "Лекция 20 — Arbeit. Büro",
      "words": [
        { "id": "w227", "de": "der Arbeitsplatz", "ru": "рабочее место", "example": "", "level": "A1" },
        { "id": "w228", "de": "der Besucher", "ru": "посетитель", "example": "", "level": "A1" },
        { "id": "w229", "de": "der Feierabend", "ru": "конец рабочего дня", "example": "", "level": "A1" },
        { "id": "w230", "de": "der Geschäftspartner", "ru": "деловой партнер", "example": "", "level": "A1" },
        { "id": "w231", "de": "der Kollege", "ru": "коллега", "example": "", "level": "A1" },
        { "id": "w232", "de": "der Kopierer", "ru": "ксерокс", "example": "", "level": "A1" },
        { "id": "w233", "de": "der Kunde", "ru": "клиент", "example": "", "level": "A1" },
        { "id": "w234", "de": "der Taschenrechner", "ru": "калькулятор", "example": "", "level": "A1" },
        { "id": "w235", "de": "der Termin", "ru": "встреча (деловая)", "example": "", "level": "A1" },
        { "id": "w236", "de": "der Terminkalender", "ru": "ежедневник, органайзер", "example": "", "level": "A1" },
        { "id": "w237", "de": "die Besprechung", "ru": "совещание, обсуждение", "example": "", "level": "A1" },
        { "id": "w238", "de": "die Geschäftsreise", "ru": "командировка", "example": "", "level": "A1" },
        { "id": "w239", "de": "die Kaffeemaschine", "ru": "кофеварка", "example": "", "level": "A1" },
        { "id": "w240", "de": "die Stelle", "ru": "место (работы), должность", "example": "", "level": "A1" },
        { "id": "w241", "de": "das Gehalt", "ru": "зарплата (служащего), оклад", "example": "", "level": "A1" },
        { "id": "w242", "de": "das Geschäft", "ru": "1. дело, бизнес; 2. магазин", "example": "", "level": "A1" },
        { "id": "w243", "de": "das Telefonat", "ru": "телефонный разговор", "example": "", "level": "A1" },
        { "id": "w244", "de": "das Team", "ru": "команда", "example": "", "level": "A1" },
        { "id": "w245", "de": "das Unternehmen", "ru": "предприятие", "example": "", "level": "A1" },
        { "id": "w246", "de": "arbeiten als ...", "ru": "работать кем-л.", "example": "", "level": "A1" },
        { "id": "w247", "de": "halbtags arbeiten", "ru": "работать неполный рабочий день", "example": "", "level": "A1" },
        { "id": "w248", "de": "vorbereiten", "ru": "готовить, подготавливать", "example": "", "level": "A1" },
        { "id": "w249", "de": "sich befinden", "ru": "находиться", "example": "", "level": "A1" },
        { "id": "w250", "de": "Telefonate führen", "ru": "вести телефонные разговоры", "example": "", "level": "A1" },
        { "id": "w251", "de": "beantworten", "ru": "отвечать", "example": "", "level": "A1" },
        { "id": "w252", "de": "schicken", "ru": "отправлять, посылать", "example": "", "level": "A1" },
        { "id": "w253", "de": "das Fax", "ru": "факс", "example": "", "level": "A1" },
        { "id": "w254", "de": "der Flug", "ru": "рейс", "example": "", "level": "A1" },
        { "id": "w255", "de": "buchen", "ru": "бронировать", "example": "", "level": "A1" },
        { "id": "w256", "de": "empfangen", "ru": "встречать, принимать", "example": "", "level": "A1" },
        { "id": "w257", "de": "Ich habe viel zu tun.", "ru": "У меня много дел.", "example": "", "level": "A1" },
        { "id": "w258", "de": "verdienen", "ru": "зарабатывать", "example": "", "level": "A1" },
        { "id": "w259", "de": "abholen", "ru": "забирать", "example": "", "level": "A1" }
      ]
    },
    {
      "id": "lektion21",
      "title": "Лекция 21 — Mensch. Körper",
      "words": [
        { "id": "w260", "de": "der Arm", "ru": "рука (от плеча до кисти)", "example": "", "level": "A1" },
        { "id": "w261", "de": "der Bauch", "ru": "живот", "example": "", "level": "A1" },
        { "id": "w262", "de": "der Finger", "ru": "палец", "example": "", "level": "A1" },
        { "id": "w263", "de": "der Fuß", "ru": "ступня", "example": "", "level": "A1" },
        { "id": "w264", "de": "der Hals", "ru": "шея", "example": "", "level": "A1" },
        { "id": "w265", "de": "der Kopf", "ru": "голова", "example": "", "level": "A1" },
        { "id": "w266", "de": "der Körper", "ru": "тело", "example": "", "level": "A1" },
        { "id": "w267", "de": "der Magen", "ru": "желудок", "example": "", "level": "A1" },
        { "id": "w268", "de": "der Mund", "ru": "рот", "example": "", "level": "A1" },
        { "id": "w269", "de": "der Rücken", "ru": "спина", "example": "", "level": "A1" },
        { "id": "w270", "de": "der Zahn", "ru": "зуб", "example": "", "level": "A1" },
        { "id": "w271", "de": "die Brust", "ru": "грудь", "example": "", "level": "A1" },
        { "id": "w272", "de": "die Hand", "ru": "рука (кисть)", "example": "", "level": "A1" },
        { "id": "w273", "de": "die Haut", "ru": "кожа", "example": "", "level": "A1" },
        { "id": "w274", "de": "die Leber", "ru": "печень", "example": "", "level": "A1" },
        { "id": "w275", "de": "die Lunge", "ru": "легкое", "example": "", "level": "A1" },
        { "id": "w276", "de": "die Nase", "ru": "нос", "example": "", "level": "A1" },
        { "id": "w277", "de": "die Niere", "ru": "почка", "example": "", "level": "A1" },
        { "id": "w278", "de": "die Zunge", "ru": "язык", "example": "", "level": "A1" },
        { "id": "w279", "de": "das Auge", "ru": "глаз", "example": "", "level": "A1" },
        { "id": "w280", "de": "das Bein", "ru": "нога", "example": "", "level": "A1" },
        { "id": "w281", "de": "das Blut", "ru": "кровь", "example": "", "level": "A1" },
        { "id": "w282", "de": "das Gesicht", "ru": "лицо", "example": "", "level": "A1" },
        { "id": "w283", "de": "das Herz", "ru": "сердце", "example": "", "level": "A1" },
        { "id": "w284", "de": "das Ohr", "ru": "ухо", "example": "", "level": "A1" },
        { "id": "w285", "de": "der Teil", "ru": "часть", "example": "", "level": "A1" },
        { "id": "w286", "de": "vorn(e)", "ru": "спереди", "example": "", "level": "A1" },
        { "id": "w287", "de": "hinten", "ru": "сзади", "example": "", "level": "A1" },
        { "id": "w288", "de": "riechen", "ru": "нюхать", "example": "", "level": "A1" },
        { "id": "w289", "de": "schmecken", "ru": "пробовать на вкус", "example": "", "level": "A1" },
        { "id": "w290", "de": "fühlen", "ru": "чувствовать", "example": "", "level": "A1" },
        { "id": "w291", "de": "beißen", "ru": "кусать", "example": "", "level": "A1" },
        { "id": "w292", "de": "kauen", "ru": "жевать", "example": "", "level": "A1" }
      ]
    },
    {
      "id": "lektion22",
      "title": "Лекция 22 — Gesundheit. Beim Arzt",
      "words": [
        { "id": "w293", "de": "der Bruch", "ru": "перелом", "example": "", "level": "A1" },
        { "id": "w294", "de": "der Durchfall", "ru": "понос", "example": "", "level": "A1" },
        { "id": "w295", "de": "der Husten", "ru": "кашель", "example": "", "level": "A1" },
        { "id": "w296", "de": "der Hustensaft", "ru": "микстура от кашля", "example": "", "level": "A1" },
        { "id": "w297", "de": "der Schmerz", "ru": "боль", "example": "", "level": "A1" },
        { "id": "w298", "de": "der Schnupfen", "ru": "насморк", "example": "", "level": "A1" },
        { "id": "w299", "de": "der Tropfen", "ru": "капля", "example": "", "level": "A1" },
        { "id": "w300", "de": "die Allergie", "ru": "аллергия", "example": "", "level": "A1" },
        { "id": "w301", "de": "die Angina", "ru": "ангина", "example": "", "level": "A1" },
        { "id": "w302", "de": "die Entzündung", "ru": "воспаление", "example": "", "level": "A1" },
        { "id": "w303", "de": "die Erkältung", "ru": "простуда", "example": "", "level": "A1" },
        { "id": "w304", "de": "die Grippe", "ru": "грипп", "example": "", "level": "A1" },
        { "id": "w305", "de": "die Krankheit", "ru": "болезнь", "example": "", "level": "A1" },
        { "id": "w306", "de": "die Salbe", "ru": "мазь", "example": "", "level": "A1" },
        { "id": "w307", "de": "die Spritze", "ru": "укол; шприц", "example": "", "level": "A1" },
        { "id": "w308", "de": "die Wunde", "ru": "рана", "example": "", "level": "A1" },
        { "id": "w309", "de": "das Fieber", "ru": "жар, высокая температура", "example": "", "level": "A1" },
        { "id": "w310", "de": "das Fiebermittel", "ru": "жаропонижающее", "example": "", "level": "A1" },
        { "id": "w311", "de": "sich erkälten", "ru": "простужаться", "example": "", "level": "A1" },
        { "id": "w312", "de": "die Sprechstunde", "ru": "прием у врача, приемные часы", "example": "", "level": "A1" },
        { "id": "w313", "de": "Was fehlt Ihnen?", "ru": "На что жалуетесь?", "example": "", "level": "A1" },
        { "id": "w314", "de": "die Beschwerde", "ru": "жалоба", "example": "", "level": "A1" },
        { "id": "w315", "de": "untersuchen", "ru": "осматривать, обследовать", "example": "", "level": "A1" },
        { "id": "w316", "de": "den Oberkörper freimachen", "ru": "раздеться до пояса", "example": "", "level": "A1" },
        { "id": "w317", "de": "tief atmen", "ru": "глубоко дышать", "example": "", "level": "A1" },
        { "id": "w318", "de": "die Lungen abhören", "ru": "слушать легкие", "example": "", "level": "A1" },
        { "id": "w319", "de": "die Temperatur messen", "ru": "измерять температуру", "example": "", "level": "A1" },
        { "id": "w320", "de": "die Diagnose stellen", "ru": "ставить диагноз", "example": "", "level": "A1" },
        { "id": "w321", "de": "krank schreiben", "ru": "выписывать больничный", "example": "", "level": "A1" },
        { "id": "w322", "de": "verschreiben", "ru": "прописывать (лекарства)", "example": "", "level": "A1" },
        { "id": "w323", "de": "Gute Besserung!", "ru": "Скорейшего выздоровления!", "example": "", "level": "A1" }
      ]
    },
    {
      "id": "lektion23",
      "title": "Лекция 23 — Jahreszeiten. Wetter",
      "words": [
        { "id": "w324", "de": "der Blitz", "ru": "молния", "example": "", "level": "A1" },
        { "id": "w325", "de": "der Donner", "ru": "гром", "example": "", "level": "A1" },
        { "id": "w326", "de": "der Frost", "ru": "мороз", "example": "", "level": "A1" },
        { "id": "w327", "de": "der Grad", "ru": "градус", "example": "", "level": "A1" },
        { "id": "w328", "de": "der Hagel", "ru": "град", "example": "", "level": "A1" },
        { "id": "w329", "de": "der Himmel", "ru": "небо", "example": "", "level": "A1" },
        { "id": "w330", "de": "der Monat", "ru": "месяц", "example": "", "level": "A1" },
        { "id": "w331", "de": "der Morgen", "ru": "утро", "example": "", "level": "A1" },
        { "id": "w332", "de": "der Nebel", "ru": "туман", "example": "", "level": "A1" },
        { "id": "w333", "de": "der Niederschlag", "ru": "осадки", "example": "", "level": "A1" },
        { "id": "w334", "de": "der Regen", "ru": "дождь", "example": "", "level": "A1" },
        { "id": "w335", "de": "der Schnee", "ru": "снег", "example": "", "level": "A1" },
        { "id": "w336", "de": "der Sturm", "ru": "буря; ураган; шторм", "example": "", "level": "A1" },
        { "id": "w337", "de": "der Wetterbericht", "ru": "прогноз погоды", "example": "", "level": "A1" },
        { "id": "w338", "de": "der Wind", "ru": "ветер", "example": "", "level": "A1" },
        { "id": "w339", "de": "die Hitze", "ru": "жара", "example": "", "level": "A1" },
        { "id": "w340", "de": "die Jahreszeit", "ru": "время года", "example": "", "level": "A1" },
        { "id": "w341", "de": "die Kälte", "ru": "холод", "example": "", "level": "A1" },
        { "id": "w342", "de": "die Luft", "ru": "воздух", "example": "", "level": "A1" },
        { "id": "w343", "de": "die Nacht", "ru": "ночь", "example": "", "level": "A1" },
        { "id": "w344", "de": "die Natur", "ru": "природа", "example": "", "level": "A1" },
        { "id": "w345", "de": "die Sonne", "ru": "солнце", "example": "", "level": "A1" },
        { "id": "w346", "de": "die Temperatur", "ru": "температура", "example": "", "level": "A1" },
        { "id": "w347", "de": "die Wolke", "ru": "облако", "example": "", "level": "A1" },
        { "id": "w348", "de": "das Gewitter", "ru": "гроза", "example": "", "level": "A1" },
        { "id": "w349", "de": "das Glatteis", "ru": "гололед", "example": "", "level": "A1" },
        { "id": "w350", "de": "das Klima", "ru": "климат", "example": "", "level": "A1" },
        { "id": "w351", "de": "das Tauwetter", "ru": "оттепель", "example": "", "level": "A1" },
        { "id": "w352", "de": "das Wetter", "ru": "погода", "example": "", "level": "A1" },
        { "id": "w353", "de": "es regnet", "ru": "идет дождь", "example": "", "level": "A1" },
        { "id": "w354", "de": "es schneit", "ru": "идет снег", "example": "", "level": "A1" },
        { "id": "w355", "de": "es hagelt", "ru": "идет град", "example": "", "level": "A1" },
        { "id": "w356", "de": "es blitzt", "ru": "сверкает молния", "example": "", "level": "A1" },
        { "id": "w357", "de": "es donnert", "ru": "гремит гром", "example": "", "level": "A1" },
        { "id": "w358", "de": "es ist bedeckt", "ru": "пасмурно", "example": "", "level": "A1" },
        { "id": "w359", "de": "es ist heiter", "ru": "ясно, безоблачно", "example": "", "level": "A1" },
        { "id": "w360", "de": "es ist windig", "ru": "ветрено", "example": "", "level": "A1" },
        { "id": "w361", "de": "es ist neblig", "ru": "туманно", "example": "", "level": "A1" },
        { "id": "w362", "de": "es ist trocken", "ru": "сухо", "example": "", "level": "A1" },
        { "id": "w363", "de": "es ist nass", "ru": "сыро", "example": "", "level": "A1" },
        { "id": "w364", "de": "es ist heiß", "ru": "жарко", "example": "", "level": "A1" },
        { "id": "w365", "de": "es ist kalt", "ru": "холодно", "example": "", "level": "A1" },
        { "id": "w366", "de": "es ist warm", "ru": "тепло", "example": "", "level": "A1" },
        { "id": "w367", "de": "es ist kühl", "ru": "прохладно", "example": "", "level": "A1" },
        { "id": "w368", "de": "sich ändern", "ru": "изменяться", "example": "", "level": "A1" },
        { "id": "w369", "de": "bald ... bald ...", "ru": "то ... то ...", "example": "", "level": "A1" },
        { "id": "w370", "de": "doch", "ru": "однако", "example": "", "level": "A1" },
        { "id": "w371", "de": "blühen", "ru": "цвести", "example": "", "level": "A1" },
        { "id": "w372", "de": "wandern", "ru": "ходить в пешие походы", "example": "", "level": "A1" },
        { "id": "w373", "de": "staubig", "ru": "пыльный", "example": "", "level": "A1" },
        { "id": "w374", "de": "das Blatt, -\"er", "ru": "лист", "example": "", "level": "A1" },
        { "id": "w375", "de": "bunt", "ru": "пестрый", "example": "", "level": "A1" }
      ]
    }
  ]
};

// === ДАННЫЕ — ТЕКСТЫ ===
window.TEXTS_DATA = {
  "meta": {
    "title": "Тексты лекций"
  },
  "texts": [
    {
      "id": "t14",
      "topic": "lektion14",
      "title": "Mein Tagesablauf",
      "full": "Mein Arbeitstag beginnt ziemlich früh. Ich stehe gewöhnlich um 6.30 Uhr auf. Nach dem Aufstehen mache ich das Bett und gehe ins Bad. Dort dusche ich und putze die Zähne.\n\nGegen 7 Uhr gehe ich in die Küche. Dort mache ich das Radio an und frühstücke. Gewöhnlich trinke ich eine Tasse Kaffee und esse ein paar Toastbrote mit Käse oder Wurst. Das Frühstück dauert nicht lange. Nach dem Frühstück spüle ich das Geschirr, packe meine Sachen und ziehe meine Jacke an. Um 7.30 Uhr gehe ich aus dem Haus.\n\nDie Schellingstraße liegt im Stadtzentrum, und die Uni ist nicht weit von meinem Haus. Bei schönem Wetter gehe ich zu Fuß, und bei schlechtem Wetter fahre ich zwei Haltestellen mit dem Bus.\n\nAn der Haltestelle \"Universität\" steige ich aus. Ich studiere Jura an der Ludwig-Maximilians-Universität. Der Unterricht an der Uni beginnt um 8 Uhr und endet gewöhnlich um 15.30 Uhr.\n\nNach dem Unterricht gehe ich in die Mensa und esse dort zu Mittag. Das Essen ist ziemlich lecker und billig. Nach dem Essen gehe ich oft in die Bibliothek. Nach der Bibliothek gehe ich manchmal direkt nach Hause, manchmal gehe ich zum Sport oder einkaufen.\n\nGegen 20 Uhr komme ich nach Hause. Zu Hause esse ich zu Abend. Dann lerne ich, surfe im Internet, lese ein bisschen oder sehe fern.\n\nAbends bin ich ziemlich müde. Um 23.00 Uhr gehe ich ins Bett und schlafe schnell ein.",
      "short": "Mein Arbeitstag beginnt früh. Um 6.30 Uhr stehe ich auf, mache das Bett, dusche und putze die Zähne. Um 7.00 Uhr frühstücke ich. Danach gehe ich aus dem Haus. Die Uni ist nicht weit, ich fahre mit dem Bus oder gehe zu Fuß. Der Unterricht dauert von 8.00 bis 15.30 Uhr. Dann esse ich in der Mensa, lerne in der Bibliothek, mache Sport oder kaufe ein. Gegen 20.00 Uhr komme ich nach Hause, esse zu Abend, lerne und sehe fern. Um 23.00 Uhr gehe ich ins Bett.",
      "translation": "Мой рабочий день начинается довольно рано. Обычно я встаю в 6:30. После того как встану, я заправляю постель и иду в ванную. Там я принимаю душ и чищу зубы.\nОколо 7 часов я иду на кухню. Там я включаю радио и завтракаю. Обычно я пью чашку кофе и ем пару тостов с сыром или колбасой. Завтрак длится недолго. После завтрака я мою посуду, собираю свои вещи и надеваю куртку. В 7:30 я выхожу из дома.\nУлица Шеллингштрассе находится в центре города, и университет недалеко от моего дома. В хорошую погоду я иду пешком, а в плохую погоду еду две остановки на автобусе.\nНа остановке «Университет» я выхожу. Я изучаю право в Мюнхенском университете имени Людвига и Максимилиана. Занятия в университете начинаются в 8 часов и обычно заканчиваются в 15:30.\nПосле занятий я иду в студенческую столовую и обедаю там. Еда довольно вкусная и дешевая. После еды я часто иду в библиотеку. После библиотеки я иногда иду сразу домой, иногда иду на спорт или за покупками.\nОколо 20 часов я возвращаюсь домой. Дома я ужинаю. Затем я учусь, сижу в интернете, немного читаю или смотрю телевизор.\nПо вечерам я довольно уставший. В 23:00 я ложусь в постель и быстро засыпаю.",
      "keywords": ["Tagesablauf", "aufstehen", "frühstücken", "Unterricht", "Mensa", "müde"]
    },
    {
      "id": "t16",
      "topic": "lektion16",
      "title": "Freizeit",
      "full": "Nach der Arbeit, am Wochenende, im Urlaub oder in den Ferien haben wir Freizeit. Aber wie kann man die Freizeit verbringen?\nMan kann zu Hause sitzen, fernsehen, Bücher lesen, Musik hören oder im Internet surfen.\nOder man kann ausgehen, ins Kino, ins Theater oder einkaufen. Zum Essen kann man ins Café oder ins Restaurant gehen. Man kann auch Museen und Ausstellungen besuchen, Sport machen oder spazieren gehen.\nIn der Woche habe ich wenig Freizeit, denn ich muss arbeiten und auch den Haushalt führen. Ich habe Freizeit am Wochenende. Man muss dann nicht arbeiten, man kann lange schlafen. Ich verbringe das Wochenende gewöhnlich mit meiner Familie. Bei schönem Wetter fahren wir oft ins Grüne und machen ein Picknick. Besonders gern fahren wir zum Fluss. Dort kann man baden, in der Sonne liegen oder Boot fahren. Das macht mir Spaß.\nBei schlechtem Wetter gehen wir ins Kino oder zu Besuch, oder wir bleiben zu Hause und laden Freunde zu einer Party ein.",
      "short": "In der Woche habe ich wenig Freizeit, ich muss arbeiten. Ich habe Freizeit am Wochenende. Dann kann man lange schlafen. Ich verbringe das Wochenende mit meiner Familie. Bei schönem Wetter fahren wir ins Grüne, baden im Fluss und liegen in der Sonne. Bei schlechtem Wetter gehen wir ins Kino, zu Besuch oder laden Freunde ein.",
      "translation": "После работы, на выходных, в отпуске или на каникулах у нас есть свободное время. Но как можно проводить свободное время?\nМожно сидеть дома, смотреть телевизор, читать книги, слушать музыку или сидеть в интернете.\nИли можно выходить в свет, в кино, в театр или за покупками. Чтобы поесть, можно пойти в кафе или ресторан. Также можно посещать музеи и выставки, заниматься спортом или гулять.\nСреди недели у меня мало свободного времени, так как я должна работать, а также вести домашнее хозяйство. У меня есть свободное время на выходных. Тогда не нужно работать, можно долго спать. Я обычно провожу выходные со своей семьей. В хорошую погоду мы часто ездим на природу и устраиваем пикник. Особенно мы любим ездить на реку. Там можно купаться, загорать или кататься на лодке. Это доставляет мне удовольствие.\nВ плохую погоду мы ходим в кино или в гости, либо остаемся дома и приглашаем друзей на вечеринку.",
      "keywords": ["Freizeit", "Wochenende", "verbringen", "Ausstellung", "Picknick", "Spaß"]
    },
    {
      "id": "t17",
      "topic": "lektion17",
      "title": "Meine Wohnung",
      "full": "Anna Meier hat eine Neuigkeit: sie zieht in eine neue Wohnung um. Das Haus liegt im Stadtzentrum in der Schellingstraße. Alle Fenster gehen auf den Hof, und der Straßenlärm stört Anna nicht. Die Wohnung liegt im vierten Stock. Leider gibt es keinen Fahrstuhl, und Anna geht die Treppe hoch und runter.\nAnnas neue Wohnung ist 82 m² (Quadratmeter) groß. Sie besteht aus drei Zimmern. Es gibt auch eine Küche, ein Badezimmer und einen Balkon. Durch die Eingangstür kommen wir in den Flur. Rechts im Flur ist eine Garderobe. Da sind auch Türen zum Bad, zur Küche und zu allen drei Zimmern.\nDas Badezimmer hat eine Badewanne, eine Toilette und ein Waschbecken. In der Ecke steht eine Waschmaschine.\nDie Küche ist ziemlich groß. Da gibt es einen Kühlschrank, einen Elektroherd, einen Geschirrspüler, eine Spüle und einige Küchenschränke. Gegenüber der Spüle steht ein Esstisch mit vier Stühlen. Über dem Tisch hängt eine Lampe. Die Wände sind weiß, und die Küche ist sehr modern.\nDas Schlafzimmer ist nicht groß, aber gemütlich. Da steht Annas Bett. Neben dem Bett steht ein Nachttisch, und gegenüber dem Bett steht ein Kleiderschrank.\nNeben dem Schlafzimmer ist das Kinderzimmer. Es ist sehr gemütlich, auf dem Fußboden liegt ein Teppich, die Tapete ist blau. An der Wand steht ein Bett, und am Fenster ist ein Schreibtisch.\nDas Wohnzimmer ist 5 mal 4 Meter groß. Jetzt richtet Anna das Wohnzimmer ein. Es ist schon tapeziert aber noch fast leer. In die Ecke will Anna ein Ecksofa mit einem Couchtisch stellen. An die Wand will sie ein paar Bilder hängen. Und sie braucht noch einen Fernseher. Bald ist das Wohnzimmer fertig. Anna ist mit ihrer Wohnung sehr zufrieden.",
      "short": "Anna zieht in eine neue Wohnung in der Schellingstraße. Die Wohnung liegt im vierten Stock. Sie ist 82 Quadratmeter groß und hat drei Zimmer, eine Küche, ein Bad und einen Balkon. Im Flur gibt es eine Garderobe und Türen zu allen Räumen. Das Badezimmer hat eine Badewanne und eine Waschmaschine. Die Küche ist groß und modern eingerichtet. Das Schlafzimmer ist gemütlich mit Bett und Schrank. Das Kinderzimmer hat einen Teppich, blaue Tapeten und einen Schreibtisch. Das Wohnzimmer richtet Anna noch ein. Dort will sie ein Ecksofa aufstellen und einen Fernseher kaufen. Anna ist mit der Wohnung sehr zufrieden.",
      "translation": "У Анны Майер новость: она переезжает в новую квартиру. Дом находится в центре города на Шеллингштрассе. Все окна выходят во двор, и шум улицы Анну не беспокоит. Квартира расположена на пятом (четвертом по-немецки) этаже. К сожалению, лифта нет, и Анна поднимается и спускается по лестнице пешком.\nНовая квартира Анны площадью 82 м² (квадратных метра). Она состоит из трех комнат. Также есть кухня, ванная комната и балкон.\nЧерез входную дверь мы попадаем в прихожую. Справа в прихожей находится гардероб. Там же находятся двери в ванную, на кухню и во все три комнаты.\nВ ванной комнате есть ванна, туалет и умывальник. В углу стоит стиральная машина.\nКухня довольно большая. Там есть холодильник, электроплита, посудомоечная машина, мойка и несколько кухонных шкафов. Напротив мойки стоит обеденный стол с четырьмя стульями. Над столом висит лампа. Стены белые, и кухня очень современная.\nСпальня небольшая, но уютная. Там стоит кровать Анны. Рядом с кроватью стоит тумбочка, а напротив кровати - платяной шкаф.\nРядом со спальней находится детская. Она очень уютная, на полу лежит ковер, обои синие. У стены стоит кровать, а у окна - письменный стол.\nГостиная размером 5 на 4 метра. Сейчас Анна обставляет гостиную. Она уже оклеена обоями, но еще почти пуста. В угол Анна хочет поставить угловой диван с журнальным столиком. На стену она хочет повесить несколько картин. И ей еще нужен телевизор. Скоро гостиная будет готова. Анна очень довольна своей квартирой.",
      "keywords": ["Wohnung", "umziehen", "Zimmer", "Küche", "Badezimmer", "einrichten"]
    },
    {
      "id": "t19",
      "topic": "lektion19",
      "title": "Ein Brief",
      "full": "Lieber Walter,\nendlich habe ich genug Zeit und schreibe Dir. Ich wollte früher schreiben, aber ich konnte nicht. Ich hatte immer keine Zeit. Das Semester war schwer, denn wir hatten viele neue Fächer, und ich hatte auch meinen Spanischkurs. Also ich schreibe Dir jetzt schon aus Spanien! Ich mache hier mein Praktikum.\nIch bin hier seit zwei Wochen, und es gefällt mir hier sehr gut. Ich bin in Barcelona und wohne fast am Meer! Ich miete hier ein Zimmer. Ich bin mit dem Zimmer sehr zufrieden. Es ist nicht groß, aber sehr gemütlich. Die Fenster gehen auf das Meer, und das ist natürlich SUPER!!! Jeden Abend bin ich am Strand, denn es ist immer sehr heiß. Die Stadt mit ihren Plätzen, Kirchen, Schlössern und natürlich mit der Sagrada Familia ist wunderbar!\nIch arbeite hier in einem Juristenbüro. Der Job gefällt mir sehr gut. Ich kenne mein Fach gut, aber es gibt manchmal Probleme mit der Sprache. Letzte Woche war bei uns ein Klient aus Deutschland, und ich musste für ihn übersetzen. Das war schwer!\nLeider liegt das Büro weit von meinem Haus. Aber ich habe Glück! Mein Mitarbeiter Pablo wohnt nicht weit von mir und fährt mich zum Büro mit seinem Auto.\nUnterwegs sprechen wir viel. So kann ich gut Spanisch üben. Er spricht sehr schnell, und ich kann ihn nicht immer verstehen. Aber er hat Geduld mit mir und wiederholt alles langsam. Das ist sehr nett von ihm.\nLeider bleibe ich nicht lange in Barcelona. Bald beende ich mein Praktikum und komme zurück nach Deutschland.\nDas war's, lieber Walter. Entschuldige, ich erzähle immer nur von mir. Wie geht es Dir und Deinen Eltern? Ich hoffe, es geht Euch gut. Was macht Deine Schwester Elke? Ich schicke Dir die neue CD von Julio Iglesias für sie. Ich weiß, sie liebt ihn sehr.\nIch wünsche Euch alles Gute!\nLiebe Grüße\nDein Felix",
      "short": "Lieber Walter, endlich habe ich Zeit und schreibe Dir aus Spanien, wo ich mein Praktikum mache. Ich wohne in Barcelona, miete ein Zimmer am Meer und bin jeden Abend am Strand, weil es sehr heiß ist. Die Stadt ist wunderbar. Ich arbeite in einem Juristenbüro und es gefällt mir gut, obwohl die Sprache manchmal schwer ist. Mein Kollege Pablo fährt mich zum Büro und wir üben Spanisch unterwegs. Bald beende ich mein Praktikum und komme zurück nach Deutschland. Wie geht es Dir und Deiner Familie? Ich schicke eine CD für Deine Schwester Elke. Ich wünsche Euch alles Gute! Dein Felix.",
      "translation": "Дорогой Вальтер,\nнаконец-то у меня есть достаточно времени, и я пишу тебе. Я хотел написать раньше, но не мог. У меня вечно не было времени. Семестр был тяжелым, так как у нас было много новых предметов, а еще у меня был курс испанского. Так что я пишу тебе уже из Испании! Я прохожу здесь практику.\nЯ здесь уже две недели, и мне тут очень нравится. Я в Барселоне и живу почти у моря! Я снимаю здесь комнату. Я очень доволен комнатой. Она небольшая, но очень уютная. Окна выходят на море, и это, конечно, СУПЕР!!! Каждый вечер я на пляже, так как всегда очень жарко. Город с его площадями, церквями, дворцами и, конечно, Саграда Фамилия - просто чудесный!\nЯ работаю здесь в юридической конторе. Работа мне очень нравится. Я хорошо знаю свою специальность, но иногда бывают проблемы с языком. На прошлой неделе у нас был клиент из Германии, и мне пришлось для него переводить. Это было тяжело!\nК сожалению, офис находится далеко от моего дома. Но мне повезло! Мой коллега Пабло живет недалеко от меня и подвозит меня до офиса на своей машине.\nПо дороге мы много разговариваем. Так я могу хорошо тренировать испанский. Он говорит очень быстро, и я не всегда могу его понять. Но у него есть терпение ко мне, и он повторяет всё медленно. Это очень мило с его стороны.\nК сожалению, я не останусь долго в Барселоне. Скоро я заканчиваю практику и возвращаюсь в Германию.\nВот и всё, дорогой Вальтер. Извини, я всегда рассказываю только о себе. Как дела у тебя и твоих родителей? Надеюсь, у вас всё хорошо. Что делает твоя сестра Эльке? Я посылаю тебе для нее новый CD Хулио Иглесиаса. Я знаю, она его очень любит.\nЖелаю вам всего хорошего!\nС наилучшими пожеланиями\nТвой Феликс",
      "keywords": ["Brief", "Praktikum", "Spanien", "Sprache", "üben", "Glück"]
    },
    {
      "id": "t20",
      "topic": "lektion20",
      "title": "Arbeit",
      "full": "Nach zwei Jahren Kinderpause kann ich wieder arbeiten, denn Franz ist jetzt im Kindergarten. Ich arbeite als Sekretärin bei der Firma STEIFF. Ich arbeite jetzt halbtags. Meine Arbeitszeit ist von 8 bis 13 Uhr.\nIch stehe um 6 Uhr auf, wasche mich und ziehe mich an. Dann bereite ich das Frühstück für mich und meinen Sohn vor. Nach dem Frühstück bringe ich Franz mit dem Auto zum Kindergarten und fahre zur Arbeit.\nMein Büro befindet sich nicht weit von meinem Haus, und ich verspäte mich fast nie zur Arbeit. Im Büro setze ich mich an meinen Schreibtisch, und die Arbeit beginnt.\nIch mache alle typischen Büroarbeiten. Ich schreibe Texte am Computer, führe Telefonate, schreibe und beantworte E-Mails, schicke Faxe und mache für meinen Chef Termine.\nUnsere Firma kooperiert mit vielen nationalen und internationalen Partnern. Für die Geschäftsreisen muss ich Termine koordinieren und Flüge und Hotelzimmer buchen. Oft kommen die Geschäftspartner auch in unsere Firma. Ich organisiere dann die Besprechungen zusammen mit meinem Chef und empfange die Gäste.\nMeine Arbeit ist nicht leicht, und ich habe immer viel zu tun. Aber das Gehalt ist nicht schlecht: ich verdiene fast 1200 Euro im Monat. Das Arbeitsklima ist auch okay. Ich verstehe mich gut mit meinen Kollegen, und wir treffen uns auch manchmal privat.\nNach Feierabend hole ich Franz vom Kindergarten ab und fahre nach Hause.",
      "short": "Nach der Kinderpause arbeite ich wieder als Sekretärin bei der Firma STEIFF. Ich arbeite halbtags von 8 bis 13 Uhr. Morgens bringe ich meinen Sohn Franz in den Kindergarten und fahre ins Büro. Ich mache typische Büroarbeiten: E-Mails schreiben, Telefonate führen und Termine machen. Oft muss ich auch Flüge und Hotelzimmer für Geschäftsreisen buchen oder Besprechungen organisieren. Ich habe immer viel zu tun, aber das Gehalt und das Arbeitsklima sind gut. Nach Feierabend hole ich meinen Sohn ab und wir fahren nach Hause.",
      "translation": "После двухлетнего декретного отпуска я снова могу работать, так как Франц теперь в детском саду. Я работаю секретарем в фирме STEIFF. Сейчас я работаю неполный рабочий день. Мое рабочее время с 8 до 13 часов.\nЯ встаю в 6 часов, умываюсь и одеваюсь. Затем я готовлю завтрак для себя и своего сына. После завтрака я отвожу Франца на машине в детский сад и еду на работу.\nМой офис находится недалеко от моего дома, и я почти никогда не опаздываю на работу. В офисе я сажусь за свой письменный стол, и работа начинается.\nЯ выполняю всю типичную офисную работу. Я набираю тексты на компьютере, веду телефонные разговоры, пишу и отвечаю на электронные письма, отправляю факсы и назначаю встречи для своего начальника.\nНаша фирма сотрудничает со многими национальными и международными партнерами. Для командировок я должна координировать встречи и бронировать авиабилеты и гостиничные номера. Часто деловые партнеры также приходят в нашу фирму. Тогда я организую совещания вместе с моим начальником и принимаю гостей.\nМоя работа не из легких, и у меня всегда много дел. Но зарплата неплохая: я зарабатываю почти 1200 евро в месяц. Рабочая атмосфера тоже нормальная. Я хорошо лажу со своими коллегами, и мы также иногда встречаемся в нерабочее время (в частном порядке).\nПосле окончания рабочего дня я забираю Франца из детского сада и еду домой.",
      "keywords": ["Arbeit", "Büro", "Termin", "Geschäftsreise", "Gehalt", "Feierabend"]
    },
    {
      "id": "t21",
      "topic": "lektion21",
      "title": "Unser Körper",
      "full": "Der Mensch hat einen Körper. Der Körper besteht aus vielen Teilen. Das sind der Kopf, der Hals, die Brust, der Bauch, der Rücken, zwei Arme und zwei Beine. Die Brust und der Bauch sind vorne, der Rücken ist hinten.\nAuf dem Kopf sind die Haare. Im Gesicht haben wir zwei Augen, eine Nase und einen Mund. Wir sehen mit den Augen und hören mit den Ohren. Wir riechen mit der Nase, schmecken mit der Zunge und fühlen mit der Haut. Wir sprechen und essen mit dem Mund und beißen und kauen mit den Zähnen.\nDer Körper hat zwei Arme und zwei Beine. Jeder Arm hat eine Hand, und jedes Bein hat einen Fuß. Die Hand hat fünf Finger. Wir gehen mit den Beinen, und wir schreiben und arbeiten mit den Händen.\nIm Körper sind viele Organe, zum Beispiel, das Herz, die Lungen, der Magen, die Leber und die Nieren.",
      "short": "Der Menschliche Körper besteht aus vielen Teilen: Kopf, Hals, Brust, Bauch, Rücken, Arme und Beine. Im Gesicht haben wir Augen, Nase und Mund. Wir sehen mit den Augen, hören mit den Ohren, riechen mit der Nase und schmecken mit der Zunge. Jeder Arm hat eine Hand mit fünf Fingern, jedes Bein hat einen Fuß. Im Körper gibt es auch viele Organe wie Herz, Lungen, Magen und Leber.",
      "translation": "У человека есть тело. Тело состоит из многих частей. Это голова, шея, грудь, живот, спина, две руки и две ноги. Грудь и живот находятся спереди, спина — сзади.\nНа голове есть волосы. На лице у нас два глаза, нос и рот. Мы видим глазами и слышим ушами. Мы нюхаем носом, чувствуем вкус языком и осязаем кожей. Мы говорим и едим ртом, откусываем и жуем зубами.\nУ тела есть две руки и две ноги. На каждой руке есть кисть, а на каждой ноге — ступня. На руке пять пальцев. Мы ходим ногами, а пишем и работаем руками.\nВ теле много органов, например, сердце, легкие, желудок, печень и почки.",
      "keywords": ["Körper", "Kopf", "Auge", "Bein", "Arm", "Organe"]
    },
    {
      "id": "t22",
      "topic": "lektion22",
      "title": "Beim Arzt",
      "full": "Mit meiner Gesundheit bin ich ganz zufrieden. Ich bin selten krank. Manchmal erkälte ich mich, gewöhnlich im Herbst oder im Winter. Dann fühle ich mich schlecht. Ich habe Husten, Halsschmerzen, Schnupfen, Kopfschmerzen und Fieber. Dann rufe ich bei der Arztpraxis an, bekomme einen Termin bei Doktor Schneider und gehe in die Sprechstunde.\n\"Was fehlt Ihnen?\", ist seine erste Frage. Ich erzähle über meine Beschwerden. Dann untersucht er mich. Zuerst soll ich den Mund öffnen und \"aaah\" sagen. Dann soll ich den Oberkörper freimachen und tief atmen. So kann der Arzt meine Lungen abhören. Danach soll ich die Temperatur messen. Manchmal soll ich auch einen Bluttest machen lassen.\nNach der Untersuchung stellt Doktor Schneider die Diagnose, schreibt mich krank und verschreibt mir die Medikamente. Ich bekomme Hustensaft gegen Husten. Ich soll stündlich einen Esslöffel Hustensaft nehmen. Gegen Schnupfen bekomme ich Nasentropfen und gegen Halsschmerzen verschreibt mir der Arzt einen Spray. Gegen Fieber bekomme ich ein Fiebermittel. Ich soll es zweimal täglich nach dem Essen nehmen. In drei Tagen soll ich wieder kommen. Zum Schluss wünscht mir der Arzt gute Besserung.",
      "short": "Ich bin selten krank, aber im Herbst oder Winter erkälte ich mich manchmal. Ich habe dann Husten, Schnupfen und Fieber. Ich gehe zu Doktor Schneider. Er untersucht mich, hört meine Lungen ab und misst die Temperatur. Er stellt eine Diagnose und verschreibt mir Medikamente: Hustensaft, Nasentropfen und ein Fiebermittel. In drei Tagen soll ich wieder kommen. Der Arzt wünscht mir gute Besserung.",
      "translation": "Своим здоровьем я вполне доволен. Я редко болею. Иногда я простужаюсь, обычно осенью или зимой. Тогда я чувствую себя плохо. У меня кашель, боль в горле, насморк, головная боль и высокая температура. Тогда я звоню в кабинет врача, записываюсь на прием к доктору Шнайдеру и иду на прием.\n\"На что жалуетесь?\", — это его первый вопрос. Я рассказываю о своих жалобах. Затем он осматривает меня. Сначала я должен открыть рот и сказать «а-а-а». Затем я должен раздеться до пояса и глубоко дышать. Так врач может послушать мои легкие. Затем я должен измерить температуру. Иногда я также должен сдать анализ крови.\nПосле осмотра доктор Шнайдер ставит диагноз, выписывает мне больничный и прописывает медикаменты. Я получаю микстуру от кашля против кашля. Я должен принимать по одной столовой ложке микстуры каждый час. От насморка я получаю капли в нос, а от боли в горле врач прописывает мне спрей. От температуры я получаю жаропонижающее. Я должен принимать его два раза в день после еды. Через три дня я должен прийти снова. В конце врач желает мне скорейшего выздоровления.",
      "keywords": ["Gesundheit", "Arzt", "Erkältung", "Fieber", "Husten", "Medikamente"]
    },
    {
      "id": "t23",
      "topic": "lektion23",
      "title": "Jahreszeiten",
      "full": "Es gibt vier Jahreszeiten. Das sind der Frühling, der Sommer, der Herbst und der Winter.\nDie Frühlingsmonate heißen der März, der April und der Mai. Die Nächte werden kürzer, und die Tage werden länger. Das Wetter im Frühling ändert sich oft, besonders im April. Bald regnet es, bald ist es sonnig. Doch das Wetter wird jeden Tag schöner. Die Frühlingsblumen blühen, und die Bäume werden grün.\nDie Sommermonate heißen der Juni, der Juli und der August. Viele Menschen mögen den Sommer, denn man kann im Sommer viel machen. Man kann baden und in der Sonne liegen. Man kann Tennis und Volleyball spielen, Rad fahren und wandern. Darum nehmen die meisten Leute ihren Urlaub im Sommer.\nIm Sommer ist es heiß, es ist oft plus 25 Grad und mehr. Es ist oft heiter und sonnig, und die Straßen sind trocken und staubig. Nur bei Gewitter wird es etwas kühler. Im Juni sind die Nächte am kürzesten und die Tage am längsten.\nDie Herbstmonate heißen der September, der Oktober und der November. Die Tage werden kürzer und die Nächte länger. Die Blätter werden bunt und fallen von den Bäumen. Im Herbst wird das Wetter schlechter. Es wird kalt und windig, und die Straßen werden schmutzig und nass. Viele Tage sind neblig, es regnet oft.\nDie Wintermonate heißen der Dezember, der Januar und der Februar. Im Winter ist es kalt, und es schneit oft. Es ist manchmal 10 Grad unter Null oder kälter. Die Flüsse und Seen bedecken sich mit Eis. Viele Menschen machen Wintersport, sie laufen Ski, Schlittschuh oder fahren Snowboard. Im Winter wird es früh dunkel und spät hell. Im Dezember sind die Nächte am längsten und die Tage am kürzesten. Aber im Januar werden die Tage schon wieder länger.",
      "short": "Es gibt vier Jahreszeiten: Frühling, Sommer, Herbst und Winter. Im Frühling ändert sich das Wetter oft. Blumen blühen und Bäume werden grün. Im Sommer ist es oft heiß und sonnig. Viele Leute machen Urlaub, baden und wandern. Im Herbst wird das Wetter schlechter, kalt und windig. Die Blätter fallen von den Bäumen. Im Winter ist es kalt, es schneit oft und man kann Wintersport machen.",
      "translation": "Существует четыре времени года. Это весна, лето, осень и зима.\nВесенние месяцы называются март, апрель и май. Ночи становятся короче, а дни — длиннее. Погода весной часто меняется, особенно в апреле. То идет дождь, то светит солнце. Однако с каждым днем погода становится всё прекраснее. Цветут весенние цветы, и деревья зеленеют.\nЛетние месяцы называются июнь, июль и август. Многие люди любят лето, потому что летом можно много чем заняться. Можно купаться и лежать на солнце. Можно играть в теннис и волейбол, кататься на велосипеде и ходить в походы. Поэтому большинство людей берут отпуск летом.\nЛетом жарко, часто бывает плюс 25 градусов и больше. Часто бывает ясно и солнечно, а улицы сухие и пыльные. Только во время грозы становится немного прохладнее. В июне ночи самые короткие, а дни самые длинные.\nОсенние месяцы называются сентябрь, октябрь и ноябрь. Дни становятся короче, а ночи длиннее. Листья становятся разноцветными и опадают с деревьев. Осенью погода портится. Становится холодно и ветрено, а улицы становятся грязными и сырыми. Многие дни туманные, часто идет дождь.\nЗимние месяцы называются декабрь, январь и февраль. Зимой холодно, и часто идет снег. Иногда бывает 10 градусов ниже нуля или холоднее. Реки и озера покрываются льдом. Многие люди занимаются зимними видами спорта, катаются на лыжах, коньках или сноуборде. Зимой рано темнеет и поздно светает. В декабре ночи самые длинные, а дни самые короткие. Но в январе дни снова становятся длиннее.",
      "keywords": ["Jahreszeiten", "Wetter", "Frühling", "Sommer", "Herbst", "Winter"]
    }
  ]
};
